title:            Poured Brews
description:      Pints of code and coding.
disqus_shortname: pourbrew
url:              http://pourbrew.co

# Owner/author information
owner:
  name:           Taylor Black
  avatar:         avatar.jpg
  bio:            "always coding. connoisseur of Library of Congress book summaries. coffee and local beer-fueled trail runner. rain for blood."
  email:          taylor@fizzyinc.com
  # Social networking links used in footer. Update and remove as you like.
  twitter: @pourbrew
  facebook: facebook.com/pourbrew
  github: @pourbrew
  stackexchange:
  linkedin:
  instagram:
  flickr:
  tumblr:
  # For Google Authorship https://plus.google.com/authorship
  google_plus:

# Analytics and webmaster tools stuff goes here
google_analytics: UA-44089530-1

google_verify: <meta name="google-site-verification" content="HhGsRt0Sj3LAjxgBhgjJVQbSFrD6YuLpbaR5HnCpHgQ" />
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in top navigation
# For external links add external: true
links:
  - title: Fizzy Inc
    url: http://fizzyinc.com
    external: true
  - title: Skora Running
    url: http://www.skorarunning.com/?acc=182be0c5cdcd5072bb1864cdee4d3d6e&bannerid=3
    external: true

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/Los_Angeles
future:      true
markdown: redcarpet
pygments: true
